class Trainer:
    def __init__(self):
        ...
    def train(self):  # Empirical risk minimization loop
        ...
    def train_until_zero_error(self):
        ...
    def random_sample_to_zero_error(self):  # For random sampling experiments
        ...
